# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4727b3c9f27cbd64ebcb989f660b4ab478cb025f48d2caa53b6a5d225981d0af618d270389aeec336998856646695f1b6397b24d9ed34da9b563f116ab55e5c0

test:
  secret_key_base: 014d5512dd1767380779e4d2dbd0f29045912b0b9724a7e3594b5e5e532c62f135683166aea411f800ee4e80f1190e5643b625ddfd51ffd445643f5bfb45b21b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
